---
title: "Open_data"
author: "Sjoerd Garssen"
date: "22/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#open csv file
setwd("M:")
raw_data=read.csv('BreastCancer.csv', skip=13)

#get X. Remove first 19 variables, as they don't have important information for the model.
X=raw_data[,-c(1:19)]

#remove a vague last variable, as it only contains NA's and is not included in the excel file.
X=X[,-ncol(X)]

#get c and convert classes to 1 (breastcancer) and -1 (no breastcancer)
c=raw_data[,10]
c=ifelse(c==0, -1,1)
```

```{r}
#repeated dcv to obtain true prediction error
modelr<-rDCV(X=X,c=c,dK=5,sK=5,p=0,A=15, r=50)

#make histogram of RMSECVs calculated on independent test set
hist1<-modelr$RMSEPs%>%hist(breaks=30, xlab = 'RMSECV')
```

```{r}
#permutation results 
random_c=c_random(c)
modelrandom=rDCV(X=X,c=random_c,dK=5,sK=5,p=0,A=15, r=50)

#make histogram 
hist2<-modelrandom$RMSEPs%>%hist(breaks=30, xlab = 'RMSECV')
```

```{r}
#Make 4 plots with x=#LV and y=RMSECV, to have an indication of Aopt of whole dataset, such that it is known which Amax should be taken in the further research.
SelectionAinrDCVk5_4<-CV(X=X,k=5,c=c,A=40, ss=23)
SelectionAinrDCVk10_4<-CV(X=X,k=10,c=c,A=40, ss=23)
plot4<-ggplot(data=SelectionAinrDCVk5_4[["performance"]],aes(x=LV,y=RMSECVs,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_4[["performance"]], aes(x=LV,y=RMSECVs,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='RMSECV', col='K-fold 1CV')

SelectionAinrDCVk5_1<-CV(X=X,k=5,c=c,A=40, ss=1)
SelectionAinrDCVk10_1<-CV(X=X,k=10,c=c,A=40, ss=1)
plot1<-ggplot(data=SelectionAinrDCVk5_1[["performance"]],aes(x=LV,y=RMSECVs,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_1[["performance"]], aes(x=LV,y=RMSECVs,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='RMSECV', col='K-fold 1CV')

SelectionAinrDCVk5_3<-CV(X=X,k=5,c=c,A=40, ss=14)
SelectionAinrDCVk10_3<-CV(X=X,k=10,c=c,A=40, ss=14)
plot3<-ggplot(data=SelectionAinrDCVk5_3[["performance"]],aes(x=LV,y=RMSECVs,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_3[["performance"]], aes(x=LV,y=RMSECVs,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='RMSECV', col='K-fold 1CV')

SelectionAinrDCVk5_2<-CV(X=X,k=5,c=c,A=40, ss=1)
SelectionAinrDCVk10_2<-CV(X=X,k=10,c=c,A=40, ss=11)
plot2<-ggplot(data=SelectionAinrDCVk5_2[["performance"]],aes(x=LV,y=RMSECVs,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_2[["performance"]], aes(x=LV,y=RMSECVs,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='RMSECV', col='K-fold 1CV')

plotsRMSECV<-ggarrange(plot1,plot2,plot3,plot4)

```

```{r}
#same as above but then with NMC instead of RMSECV
plot1<-ggplot(data=SelectionAinrDCVk5_1[["performance"]],aes(x=LV,y=NMC,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_1[["performance"]], aes(x=LV,y=NMC,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='NMC', col='K-fold 1CV')

plot2<-ggplot(data=SelectionAinrDCVk5_2[["performance"]],aes(x=LV,y=NMC,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_2[["performance"]], aes(x=LV,y=NMC,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='NMC', col='K-fold 1CV')

plot3<-ggplot(data=SelectionAinrDCVk5_3[["performance"]],aes(x=LV,y=NMC,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_3[["performance"]], aes(x=LV,y=NMC,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='NMC', col='K-fold 1CV')

plot4<-ggplot(data=SelectionAinrDCVk5_4[["peplotrformance"]],aes(x=LV,y=NMC,col='K=5'))+geom_line()+geom_line(data=SelectionAinrDCVk10_4[["performance"]], aes(x=LV,y=NMC,col='K=10'))+labs(title='1CV of whole data set',x='#Components in model',y='NMC', col='K-fold 1CV')

plotsNMC<-ggarrange(plot1,plot2,plot3,plot4)
```

```{r}
#TESTING
small1<-smallsample(X=X,c=c,n=50,ss=1,bal=1)
small1X<-small1[['small']][['Xsmall']]
small1c<-small1[['small']][['csmall']]
CV(X=small1X,k=5,c=small1c,A=15,ss=1)

```
```{r}
#TESTING
DCV(X=small1X,c=small1c,A=15,dK=50,sK=49,p=0,ss=1,method='RMSECV')
```

```{r}
#execute DCV and make plot of predicted and true c (WHOLE DATA SET)
largedcv<-DCV(X=X,c=c,sK=5,dK=5,A=15,p=0,ss=1,method='RMSECV')
largedcv[["predcandtruec"]]%>%ggplot(aes(x=pred, y=true))+geom_point()+geom_vline(xintercept=0,col='red')
```

```{r}
#TESTING LV SELECTION WITH B ANGLE
angle_LVselection<-function(X,c,A){
  b=matrix(NA,ncol=A,nrow=ncol(X))
  for (a in 1:A){
    model=plsda_function(X,c,a)
    b[,a]=model$regressioncoefficient
  }
  df=data.frame(LV=c(1:(A-1)),angles=NA)
  for (i in 2:A){
    ang=angle(b[,i-1],b[,i])
    df[i-1,2]=ang
  }
  return(df)
}
angle_LVselection(X,c,A=15)
```

```{r}
#make histogram of chosen Aopt with 20 small data sets
matrix=data.frame(Aopt=NA)
for (i in 1:20){
  small=smallsample(X=X,c=c,n=50,ss=i,bal=1)
  smallX=small[['small']][['Xsmall']]
  smallc=small[['small']][['csmall']]
  Aopt=LV_select(X=smallX,k=50,c=smallc,A=15,p=0.05,ss=i,method='DQ2')
  matrix[,i]=Aopt
}
plot5<-data.frame(Aopt=t(matrix))%>%ggplot(aes(x=Aopt))+geom_histogram(bins=4, binwidth = 0.5
```

```{r}
#make data frames with Aopt, RMSEP and ACC based on small data set and tested on whole data set.
RMSECVvalues=data.frame(Aopt=NA,RMSEP=NA,acc=NA)
NMCvalues=data.frame(Aopt=NA,RMSEP=NA,acc=NA)
for (i in 1:20){
  #make small sample
  small=smallsample(X=X,c=c,n=50,ss=i,bal=1)
  smallX=small[['small']][['Xsmall']]
  smallc=small[['small']][['csmall']]
  
  #select Aopt with RMSECV or NMC and save in dataframe
  Aopt=LV_select(X=smallX,k=50,c=smallc,A=15,p=0,ss=i,method='RMSECV')+1
  Aopt_NMC=LV_select(X=smallX,k=50,c=smallc,A=15,p=0,ss=i,method='NMC')+1
  RMSECVvalues[i,1]=Aopt
  NMCvalues[i,1]=Aopt_NMC
  
  #make model with Aopt selected with RMSECV and NMC
  model=plsda_function(X=smallX,c=smallc,A=Aopt)
  model_NMC=plsda_function(X=smallX,c=smallc,A=Aopt_NMC)
  
  #make prediction of whole data set
  pred=prediction(X=X,m=model)
  pred_NMC=prediction(X=X,m=model_NMC)
  
  #calculate RMSEP on large data set and save in data frame
  RMSEP=sqrt(sum((c-pred)^2)/nrow(X))
  RMSEP_NMC=sqrt(sum((c-pred_NMC)^2)/nrow(X))
  RMSECVvalues[i,2]=RMSEP
  NMCvalues[i,2]=RMSEP_NMC
  
  #predict class with threshold from model
  predclass=ifelse(pred>model$threshold,1,-1)
  predclass_NMC=ifelse(pred_NMC>model_NMC$threshold,1,-1)
  
  #calculate accuracies for both models and store value
  good=0
  for (j in 1:nrow(X)){
    if (predclass[j]==c[j]){
      good=good+1
    } else {
      good=good
    }
  }
  acc=100*good/nrow(X)
  RMSECVvalues[i,3]=acc
  good=0
  for (l in 1:nrow(X)){
    if (predclass_NMC[l]==c[l]){
      good=good+1
    } else {
      good=good
    }
  }
  acc_NMC=100*good/nrow(X)
  NMCvalues[i,3]=acc_NMC
}
```

```{r}
#make plots for Aopt selection based on RMSECV
for (i in 1:4){
  small=smallsample(X=X,c=c,n=50,ss=i,bal=1)
  smallX=small[['small']][['Xsmall']]
  smallc=small[['small']][['csmall']]
  cv=CV(X=smallX,k=50,c=smallc,A=15,ss=i)
  plot=cv$performance%>%ggplot(aes(x=LV,y=DQ2))+geom_line()
  #plot=cv$RMSECV_plot
  plot(plot)
}
```

```{r}
#Take 50 small sets. For every set determine Aopt, make a model on whole small data set and test on whole large data set. Here: Aopt selection with RMSECV
performance_RMSECV=modelselectionperformance(X=X,c=c,n=50,bal=1,k=50,A=15,p=0,method='RMSECV',r=50)
performance_RMSECV
```


```{r}
#here: Aopt selection with NMC or DQ2
performance_NMC=modelselectionperformance(X=X,c=c,n=50,bal=1,k=50,A=15,p=0,method='NMC',r=50)
performance_DQ2=modelselectionperformance(X=X,c=c,n=50,bal=1,k=50,A=15,p=0,method='DQ2',r=50)
```

```{r}
#make eroor plot RMSEP values
DQ2_mean=performance_DQ2$RMSEP%>%mean()
DQ2_sd=performance_DQ2$RMSEP%>%sd()
RMSECV_mean=performance_RMSECV$RMSEP%>%mean()
RMSECV_sd=performance_RMSECV$RMSEP%>%sd()
NMC_mean=performance_NMC$RMSEP%>%mean()
NMC_sd=performance_NMC$RMSEP%>%sd()
perf=data.frame(Method=c('DQ2','RMSECV','NMC'),RMSEP_mean=c(DQ2_mean,RMSECV_mean, NMC_mean),RMSEP_sd=c(DQ2_sd,RMSECV_sd,NMC_sd))
```

```{r}
#calculate means and sds of accuracy
DQ2_mean=performance_DQ2$ACC%>%mean()
DQ2_sd=performance_DQ2$ACC%>%sd()
RMSECV_mean=performance_RMSECV$ACC%>%mean()
RMSECV_sd=performance_RMSECV$ACC%>%sd()
NMC_mean=performance_NMC$ACC%>%mean()
NMC_sd=performance_NMC$ACC%>%sd()
perf2=data.frame(Method=c('DQ2','RMSECV','NMC'),ACC_mean=c(DQ2_mean,RMSECV_mean, NMC_mean),ACC_sd=c(DQ2_sd,RMSECV_sd,NMC_sd))
```

```{r}
perf2[4,c(2,3)]=c(modelr$ACC_mean,modelr$ACC_sd)
perf2$Method=c(perf$method)
perf2[,2]<-perf2[,2]%>%as.numeric()
perf2[,3]<-perf2[,3]%>%as.numeric()
plot6<-ggplot(perf2,aes(x=Method,y=ACC_mean, ymin=ACC_mean-ACC_sd,ymax=ACC_mean+ACC_sd))+geom_crossbar()
```


